### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by k4b7** [Khan/flow-to-ts#79]
- [ ] improve conversion
  - [x] convert Flow types for React to TypeScript types (#90)
  - [x] handle `declare` syntax (#41)
  - [x] handle function/method overloading (#40)
  - [x] handle recursive types (#69)
  - [x] handle callables (#128)
  - [x] handle explicit inexact object type syntax (#137)
- [ ] improve command line tool
  - [ ] add `utility-types` to package.json (#202)
  - [ ] add `@types/*` to package.json (#50)
  - [ ] create tsconfig.json (#203)
  - [ ] remove `flow-typed` and `.flowconfig` (#50) 
  - [ ] use prettier options from .prettierrc (#78)
- [ ] test that type errors match between Flow and TypeScript code (#83)
- [ ] convert TypeScript to Flow
